exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: DASIP 2022
description: Workshop on Design and Architectures for Signal and Image Processing in conjunction with the 17th HiPEAC Conference